services:
  - type: web
    name: block-e-gestimmeuble
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: block-e-db
          property: connectionString
      - key: FLASK_ENV
        value: production
